export const LEER_INPUT = 'LEER_INPUT';
export const GUARDAR_DATOS_USUARIO = 'GUARDAR_DATOS_USUARIO';
export const GUARDAR_REPOSITORIOS_USUARIO = 'GUARDAR_REPOSITORIOS_USUARIO';
export const LIMPIAR_DATOS = 'LIMPIAR_DATOS';